version: 3

pullapprove_conditions:
#  - "'WIP' not in title"
  - "base.ref == 'staging'"
  - "'hotfix' not in labels"
  - condition: "body and '- [ ]' not in body"
    unmet_status: pending
    explanation: "Please finish all the tasks first"
  - condition: "'WIP' not in title"
    unmet_status: pending
    explanation: "Work in progress"
  - condition: "not draft"
    unmet_status: pending
    explanation: "Work in progress"


notifications:
  - when: pull_request.opened
    comment: |
      @{{ author }}, thanks for the PR! The review will start once
      all tasks have been completed and the proper labels are applied.
      If you haven't, please make sure to read the handbook section on
      [contributing](https://primetrust-handbook.netlify.app/docs/#/?id=contributing-to-the-codebase)



  - when: pullapprove.approved # groups.users.first? users.in.group ?
    comment: "Test tech_lead name: @{{ groups.approved.include('*_techlead') }}"
#    comment: "The review is completed. @{{ author }}, please merge this in when ready."

groups:
  compliance:
    conditions:
      - "'compliance' in labels"
    reviewers:
      teams: [ team-l2c2 ]
      users:
        - thorncp

  custody:
    conditions:
      - "'custody' in labels"
    reviews:
      required: 2
      request: 2
    reviewers:
      teams: [ team-l2c2 ]

  indemnity:
    conditions:
      - "'indemnity' in labels"
    reviewers:
      teams: [ team-iris ]
      users:
        - jhakoopian

  issuance:
    conditions:
      - "'issuance' in labels"
    reviewers:
      teams: [ team-iris ]
      users:
        - JibranKalia

  ledger:
    conditions:
      - "'ledger' in labels"
    reviewers:
      teams: [ team-l2c2 ]
      users:
        - jfedger

  liquidity:
    conditions:
      - "'liquidity' in labels"
    reviews:
      required: 2
      request: 2
    reviewers:
      teams: [ team-l2c2 ]
#      users:
#        - dollerbill

  other: # security, integrator/ dev experience, FA, internal tool/ backoffice
    conditions:
      - "'other' in labels"
    reviewers:
      teams: [ team-l2c2, team-iris ]

  rails:
    conditions:
      - "'rails' in labels"
    reviewers:
      teams: [ team-iris ]
      users:
        - JibranKalia

  settlement:
    conditions:
      - "'settlement' in labels"
    reviewers:
      teams: [ team-iris ]
      users:
        - ~davidzhangpt

#  dev:
#    reviewers:
#      users:
#        - username
#      teams:
#        - developers
#    reviews:
#      required: 2  # number of approvals required from this group
#      request: 1  # number of review requests sent at a time
#      request_order: random  # "random" or "given"
#    labels:
#      approved: "Code review approved"

####################
#### Team Leads ####
####################
# Each tech lead is set as their own group that will be tagged
# after their corresponding team has approved the initial reviews.
  compliance_techlead:
    conditions:
      - "'compliance' in labels"
      - "'team-l2c2' in groups.passing"
    labels:
      approved: "Merge me blazer"

    reviewers:
      users:
        - thorncp

  custody_techlead:
    conditions:
      - "'custody' in labels"
      - "'team-l2c2' in groups.passing"
    reviewers:
      users:
        - jfedger

  indemnity_techlead:
    conditions:
      - "'indemnity' in labels"
      - "'team-iris' in groups.passing"
    reviewers:
      users:
        - jhakoopian

  issuance_techlead:
    conditions:
      - "'issuance' in labels"
      - "'team-iris' in groups.passing"
    reviewers:
      users:
        - JibranKalia

  ledger_techlead:
    conditions:
      - "'ledger' in labels"
      - "'team-l2c2' in groups.passing"
    reviewers:
      users:
        - jfedger

  liquidity_techlead:
    conditions:
      - "'liquidity' in labels"
      - "'team-l2c2' in groups.passing"
#      - len(groups.approved) >= 2
#      - len(groups.approved.include('team-l2c2')) >= 2
      # this group is asked to review if no previous groups match this PR
      - "len(groups.active) == 0"  # or "not groups.active"
    reviewers:
      users:
        - mculp

  rails_techlead:
    conditions:
      - "'rails' in labels"
      - "'team-iris' in groups.passing"
#    labels:
#      approved: "Ready to merge"
    reviewers:
      users:
        - JibranKalia
