version: 3

pullapprove_conditions:
  - "'WIP' not in title"
  - "base.ref == 'staging'"
  - "'hotfix' not in labels"

notifications:
  - when: pull_request.opened
    comment: "The review is completed. @{{ author }}, please merge this in when ready."
#
#    comment: >
#      @{{ author }}, please make sure rubocop and the entire testsuite passes.

  - when: pullapprove.approved
    comment: "The review is completed. @{{ author }}, please merge this in when ready."

groups:
  compliance:
    conditions:
      - "'compliance' in labels"
    reviewers:
      teams: [ team-l2c2 ]
      users:
        - thorncp

  custody:
    conditions:
      - "'custody' in labels"
    reviewers:
      teams: [ team-l2c2 ]
      users:
        - jfedger

  indemnity:
    conditions:
      - "'indemnity' in labels"
    reviewers:
      teams: [ team-iris ]
      users:
        - jhakoopian

  issuance:
    conditions:
      - "'issuance' in labels"
    reviewers:
      teams: [ team-iris ]
      users:
        - JibranKalia

  ledger:
    conditions:
      - "'ledger' in labels"
    reviewers:
      teams: [ team-l2c2 ]
      users:
        - jfedger

  liquidity:
    conditions:
      - "'liquidity' in labels"
    reviews:
      required: 2
      request: 2
    reviewers:
      teams: [ team-rails ]
      users:
        - mculp

  other: # security, integrator/ dev experience, FA, internal tool/ backoffice
    conditions:
      - "'other' in labels"
    reviewers:
      teams: [ team-l2c2, team-iris ]

  rails:
    conditions:
      - "'rails' in labels"
    reviewers:
      teams: [ team-iris ]
      users:
        - JibranKalia

  settlement:
    conditions:
      - "'settlement' in labels"
    reviewers:
      teams: [ team-iris ]
      users:
        - ~davidzhangpt

#  dev:
#    reviewers:
#      users:
#        - username
#      teams:
#        - developers
#    reviews:
#      required: 2  # number of approvals required from this group
#      request: 1  # number of review requests sent at a time
#      request_order: random  # "random" or "given"
#    labels:
#      approved: "Code review approved"


  rails_techlead:
    conditions:
      # only asked to review once the other 2 groups are finished (or not applicable)
      - "'developers' in groups.passing"
      - "'database' in groups.passing"
    reviewers:
      users:
        - JibranKalia
